# Generated by Django 6.0.6 on 2026-06-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('medium', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField()),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('series', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('story', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=120)),
                ('creation_time', models.CharField(blank=True, max_length=100)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('not_for_sale', 'Not for Sale')], default='available', max_length=20)),
                ('image', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
