# Generated by Django 6.0.6 on 2026-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_remove_artwork_series_artwork_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
