# Generated by Django 6.0.6 on 2026-06-14 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artwork_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='edition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artwork',
            name='framing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='artworks.artwork')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='artworks.artwork')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkSymbolismEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('meaning', models.CharField(max_length=255)),
                ('swatch', models.CharField(blank=True, max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbolism_entries', to='artworks.artwork')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
